name: generate github stats

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  
  # allows to manually run the job at any time
  workflow_dispatch:
  
  # run on every push on the master branch
  push:
    branches:
    - master

env:
  DEVOPS_DIR: github-stats
  
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    
    steps:
    # Check out repository under $GITHUB_WORKSPACE, so the job can access it
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: SaegusaMayumi1234/github-stats
        token: ${{ secrets.GITHUB_TOKEN }}
        # path: ${{ env.DEVOPS_DIR }}
    
    # Run using Python 3.8 for consistency and aiohttp
    - name: Set up python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: 'x64'
        cache: 'pip'

    # Install dependencies with `pip`
    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt

    # Generate all statistics images
    - name: Generate images
      run: |
        python3 --version
        python3 generate_images.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        EXCLUDE_FORKED_REPOS: true

    # push the content of <build_dir> to a branch
    # the content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file> , or as github page
    - name: Push to the output branch
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
        target_branch: github-stats
        build_dir: generated
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
